name: Check PR title conforms to conventional commits format

on:
  pull_request:
    branches: [ master ]
    types: [opened, edited, synchronize, reopened]

jobs:
  commitlint:
    name: Check PR title
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Verify PR title is in the correct format
        run: |
          echo "${{ github.event.pull_request.title }}" | npx commitlint -V
