name: JRuby

on:
  push:
    branches: [ master, jruby ]
  pull_request:
    branches: [ master ]

jobs:

  jruby:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 'jruby-9.2.14.0'
        gemfile:
          - rails6.0.gemfile
          - rails6.1.gemfile

    # Has to be top level to cache properly
    env:
      BUNDLE_GEMFILE: "gemfiles/${{ matrix.gemfile }}"
      BUNDLE_JOBS: 4
      BUNDLE_PATH: "vendor/bundle"
      BUNDLE_WITHOUT: "development"
    steps:
    - uses: actions/checkout@v2
    - name: Set up JRuby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Build and test jruby
      run: |
        bundle exec rake spec:integrations spec:units
